version: '3.6'
services:
  web:
    labels:
      - traefik.enable=true
      ## HTTP Services
      - traefik.http.services.{{name}}-svc.loadbalancer.server.port=80

  {{#each sites as |site code|}}
      ## {{code}} => {{code}}.bioland.cbddev.xyz
      - traefik.http.routers.b-{{../name}}-{{code}}-rtr.entrypoints=https
      - traefik.http.routers.b-{{../name}}-{{code}}-rtr.rule=Host(`{{code}}.bioland.cbddev.xyz`)
      - traefik.http.routers.b-{{../name}}-{{code}}-rtr.service={{../name}}-svc
      - traefik.http.routers.b-{{../name}}-{{code}}-rtr.tls.certResolver=le
      
  {{/each}}
    external_links:
      - load-balancer_traefik_1
    networks:
      - webgateway
      - ddev_default
{{#unless isLocal}}
  db:
    deploy:
      resources:
          limits:
            cpus: "0.50"
            memory: 1536M
{{/unless}}
networks:
  webgateway:
    external: true
    name: webgateway
  ddev_default:
    external: true
    name: ddev_default
  default:
    external: true
    name: webgateway