version: '3.6'
services:
  web:
    labels:
      - traefik.enable=true
      ## HTTP Services
      - traefik.http.services.{{name}}-svc.loadbalancer.server.port=80

      ## HTTP Routers router.name = b-${branchName}-${subDomain}-${countryCode} // uniqure router definition via name

  {{#each sites as |site code|}}

      {{#unless site.environment}}
      {{#if site.redirectTo}}
      ## {{code}} => main url {{site.redirectTo}}
      - traefik.http.routers.b-{{../name}}-{{code}}-redirect-base-rtr.entrypoints=https
      - traefik.http.routers.b-{{../name}}-{{code}}-redirect-base-rtr.rule=Host(`{{site.redirectTo}}`)
      - traefik.http.routers.b-{{../name}}-{{code}}-redirect-base-rtr.service={{../name}}-svc
      - traefik.http.routers.b-{{../name}}-{{code}}-redirect-base-rtr.priority={{../routePriority}}

      {{/if}}
      {{#unless site.redirectTo}}
      ## {{code}} => {{code}}.chm-cbd.net
      - traefik.http.routers.b-{{../name}}-{{code}}-rtr.entrypoints=https
      - traefik.http.routers.b-{{../name}}-{{code}}-rtr.rule=Host(`{{code}}.chm-cbd.net`)
      - traefik.http.routers.b-{{../name}}-{{code}}-rtr.service={{../name}}-svc
      - traefik.http.routers.b-{{../name}}-{{code}}-rtr.priority={{../routePriority}}

      {{/unless}}

      - traefik.http.middlewares.b-{{../name}}-{{code}}-test-mw.redirectregex.regex=https://{{code}}.test.chm-cbd.net/(.*)
      - traefik.http.middlewares.b-{{../name}}-{{code}}-test-mw.redirectregex.replacement=https://{{code}}.chm-cbd.net/$${1}
      - traefik.http.middlewares.b-{{../name}}-{{code}}-test-mw.redirectregex.permanent=true

      - traefik.http.routers.b-{{../name}}-{{code}}-test-rtr.entrypoints=https
      - traefik.http.routers.b-{{../name}}-{{code}}-test-rtr.rule=Host(`{{code}}.test.chm-cbd.net`)
      - traefik.http.routers.b-{{../name}}-{{code}}-test-rtr.service={{../name}}-svc
      - traefik.http.routers.b-{{../name}}-{{code}}-test-rtr.priority={{../routePriority}}
      - traefik.http.routers.b-{{../name}}-{{code}}-test-rtr.middlewares=b-{{../name}}-{{code}}-test-mw
      {{/unless}}
      {{#if site.environment}}
      ## {{code}} => {{code}}.test.chm-cbd.net
      - traefik.http.routers.b-{{../name}}-{{code}}-t-rtr.entrypoints=https
      - traefik.http.routers.b-{{../name}}-{{code}}-t-rtr.rule=Host(`{{code}}.test.chm-cbd.net`)
      - traefik.http.routers.b-{{../name}}-{{code}}-t-rtr.service={{../name}}-svc
      - traefik.http.routers.b-{{../name}}-{{code}}-t-rtr.priority={{../routePriority}}

      {{/if}}
    
    {{#if site.redirectTo}}
    {{#if (neq site.redirectTo (concat code '.chm-cbd.net'))}}
      ## {{code}} => {{code}}.chm-cbd.net redirect to {{site.redirectTo}} {{url}}
      - traefik.http.middlewares.b-{{../name}}-{{code}}-rdt-mw.redirectregex.regex=https://{{code}}.chm-cbd.net/(.*)
      - traefik.http.middlewares.b-{{../name}}-{{code}}-rdt-mw.redirectregex.replacement=https://{{site.redirectTo}}/$${1}
      - traefik.http.middlewares.b-{{../name}}-{{code}}-rdt-mw.redirectregex.permanent=true

      - traefik.http.routers.b-{{../name}}-{{code}}-rtr.entrypoints=https
      - traefik.http.routers.b-{{../name}}-{{code}}-rtr.rule=Host(`{{code}}.chm-cbd.net`)
      - traefik.http.routers.b-{{../name}}-{{code}}-rtr.service={{../name}}-svc
      - traefik.http.routers.b-{{../name}}-{{code}}-rtr.priority=0
      - traefik.http.routers.b-{{../name}}-{{code}}-rtr.middlewares=b-{{../name}}-{{code}}-rdt-mw
      ##
    {{/if}}
    {{/if}}

    {{#each site.urls as |url index|}}
      {{#unless site.redirectTo}}
      ## {{code}} => {{url}}
      - traefik.http.routers.b-{{../../name}}-{{code}}-{{index}}-rtr.entrypoints=https
      - traefik.http.routers.b-{{../../name}}-{{code}}-{{index}}-rtr.rule=Host(`{{url}}`)
      - traefik.http.routers.b-{{../../name}}-{{code}}-{{index}}-rtr.service={{../../name}}-svc
      - traefik.http.routers.b-{{../../name}}-{{code}}-{{index}}-rtr.priority={{../../routePriority}}

      {{/unless}}
      {{#if site.redirectTo}}

      ## {{code}} => {{url}} redirect to {{site.redirectTo}}
      - traefik.http.middlewares.b-{{../../name}}-{{code}}-{{index}}-mw.redirectregex.regex=https://{{url}}/(.*)
      - traefik.http.middlewares.b-{{../../name}}-{{code}}-{{index}}-mw.redirectregex.replacement=https://{{site.redirectTo}}/$${1}
      - traefik.http.middlewares.b-{{../../name}}-{{code}}-{{index}}-mw.redirectregex.permanent=true

      - traefik.http.routers.b-{{../../name}}-{{code}}-{{index}}-rtr.entrypoints=https
      - traefik.http.routers.b-{{../../name}}-{{code}}-{{index}}-rtr.rule=Host(`{{url}}`)
      - traefik.http.routers.b-{{../../name}}-{{code}}-{{index}}-rtr.service={{../../name}}-svc
      - traefik.http.routers.b-{{../../name}}-{{code}}-{{index}}-rtr.priority=0
      - traefik.http.routers.b-{{../../name}}-{{code}}-{{index}}-rtr.middlewares=b-{{../../name}}-{{code}}-{{index}}-mw

      {{/if}}
    {{/each}}
  {{/each}}
    external_links:
      - load-balancer_traefik_1
    networks:
      - webgateway
      - ddev_default
networks:
  webgateway:
    external: true
    name: webgateway
  ddev_default:
    external: true
    name: ddev_default
  default:
    external: true
    name: webgateway